# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from collections import deque
import random
import sqlite3
con = sqlite3.connect('question.db')
cur = con.cursor()
cur.execute("CREATE TABLE IF NOT EXISTS question (qtext text, A1 text, A2 text, A3 text, A4 text, A5 text, Answer1 int(10), Answer2 int(10), aCount int(10))")

class Ui_MainWindow(object):
    sql_select_all = '''select * from question'''
    cur.execute(sql_select_all)
    sqlfetchall = cur.fetchall()
    random.shuffle(sqlfetchall)
    current_index = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(30, 40, 581, 112))
        self.question.setWordWrap(True)
        self.question.setObjectName("question")
        self.Bu1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bu1.setGeometry(QtCore.QRect(30, 170, 31, 23))
        self.Bu1.setObjectName("Bu1")
        self.Bu2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bu2.setGeometry(QtCore.QRect(30, 260, 31, 23))
        self.Bu2.setObjectName("Bu2")
        self.Bu3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bu3.setGeometry(QtCore.QRect(30, 350, 31, 23))
        self.Bu3.setObjectName("Bu3")
        self.Bu4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bu4.setGeometry(QtCore.QRect(30, 440, 31, 23))
        self.Bu4.setObjectName("Bu4")
        self.A1 = QtWidgets.QLabel(self.centralwidget)
        self.A1.setGeometry(QtCore.QRect(70, 170, 371, 70))
        self.A1.setWordWrap(True)
        self.A1.setObjectName("A1")
        self.A2 = QtWidgets.QLabel(self.centralwidget)
        self.A2.setGeometry(QtCore.QRect(70, 260, 371, 70))
        self.A2.setWordWrap(True)
        self.A2.setObjectName("A2")
        self.A4 = QtWidgets.QLabel(self.centralwidget)
        self.A4.setGeometry(QtCore.QRect(70, 440, 371, 70))
        self.A4.setWordWrap(True)
        self.A4.setObjectName("A4")
        self.A3 = QtWidgets.QLabel(self.centralwidget)
        self.A3.setGeometry(QtCore.QRect(70, 350, 371, 70))
        self.A3.setWordWrap(True)
        self.A3.setObjectName("A3")
        self.NextButton = QtWidgets.QPushButton(self.centralwidget)
        self.NextButton.setGeometry(QtCore.QRect(554, 530, 81, 41))
        self.NextButton.setObjectName("NextButton")
        self.PrivButton = QtWidgets.QPushButton(self.centralwidget)
        self.PrivButton.setGeometry(QtCore.QRect(460, 530, 81, 41))
        self.PrivButton.setObjectName("PrivButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 61, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 440, 81, 61))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 380, 161, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(496, 410, 161, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 440, 81, 61))
        self.pushButton.setObjectName("pushButton")
        self.Bu5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bu5.setGeometry(QtCore.QRect(30, 530, 31, 23))
        self.Bu5.setObjectName("Bu5")
        self.A5 = QtWidgets.QLabel(self.centralwidget)
        self.A5.setGeometry(QtCore.QRect(70, 530, 371, 70))
        self.A5.setWordWrap(True)
        self.A5.setObjectName("A5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.A1.setAlignment(QtCore.Qt.AlignLeft)
        self.A2.setAlignment(QtCore.Qt.AlignLeft)
        self.A3.setAlignment(QtCore.Qt.AlignLeft)
        self.A4.setAlignment(QtCore.Qt.AlignLeft)
        self.A5.setAlignment(QtCore.Qt.AlignLeft)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.NextButton.clicked.connect(self.nextButton)
        self.PrivButton.clicked.connect(self.privButton)
        self.Bu1.clicked.connect(lambda: self.chooseNum(1))
        self.Bu2.clicked.connect(lambda: self.chooseNum(2))
        self.Bu3.clicked.connect(lambda: self.chooseNum(3))
        self.Bu4.clicked.connect(lambda: self.chooseNum(4))
        self.Bu5.clicked.connect(lambda: self.chooseNum(5))
        self.pushButton.clicked.connect(self.showAnswer)
        global listA
        listA = deque(maxlen=2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.question.setText(_translate("MainWindow", "다음버튼을 눌러주세요"))
        self.Bu1.setText(_translate("MainWindow", ""))
        self.Bu2.setText(_translate("MainWindow", ""))
        self.Bu3.setText(_translate("MainWindow", ""))
        self.Bu4.setText(_translate("MainWindow", ""))
        self.A1.setText(_translate("MainWindow", ""))
        self.A2.setText(_translate("MainWindow", ""))
        self.A4.setText(_translate("MainWindow", ""))
        self.A3.setText(_translate("MainWindow", ""))
        self.NextButton.setText(_translate("MainWindow", "다음"))
        self.PrivButton.setText(_translate("MainWindow", "이전"))
        self.pushButton.setText(_translate("MainWindow", "정답확인"))
        self.label_6.setText(_translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", ""))
        self.Bu5.setText(_translate("MainWindow", ""))
        self.A5.setText(_translate("MainWindow", ""))
        self.label_7.setText(_translate("MainWindow", ""))
        self.label_8.setText(_translate("MainWindow", "내가 고른 답: "))
        self.label_9.setText(_translate("MainWindow", "정  답: "))

    # 다음버튼
    def nextButton(self):
        listA.clear()
        self.label_8.setText("내가 고른 답: ")
        self.label_9.setText("정  답: ")
        global current_index
        if self.current_index == 216:
            self.current_index += 0
        else:
            self.current_index += 1
        self.label_6.setText(str(self.current_index) + "/216")
        if self.current_index >= len(self.sqlfetchall):
            return
        if (self.sqlfetchall[self.current_index][5] is None):
            self.A5.setText("")
            self.Bu5.setText("")
        else:
            self.A5.setText(self.sqlfetchall[self.current_index][5][5:])
            self.Bu5.setText(self.sqlfetchall[self.current_index][5][1:2])
        self.question.setText(self.sqlfetchall[self.current_index][0])
        self.A1.setText(self.sqlfetchall[self.current_index][1][5:])
        self.A2.setText(self.sqlfetchall[self.current_index][2][5:])
        self.A3.setText(self.sqlfetchall[self.current_index][3][5:])
        self.A4.setText(self.sqlfetchall[self.current_index][4][5:])
        self.Bu1.setText(self.sqlfetchall[self.current_index][1][1:2])
        self.Bu2.setText(self.sqlfetchall[self.current_index][2][1:2])
        self.Bu3.setText(self.sqlfetchall[self.current_index][3][1:2])
        self.Bu4.setText(self.sqlfetchall[self.current_index][4][1:2])

    # 이전버튼
    def privButton(self):
        listA.clear()
        self.label_8.setText("내가 고른 답: ")
        self.label_9.setText("정  답: ")
        global current_index
        if self.current_index <= 1:
            return
        self.current_index -= 1
        self.label_6.setText(str(self.current_index) + "/216")
        if self.current_index >= len(self.sqlfetchall):
            return
        if (self.sqlfetchall[self.current_index][5] is None):
            self.A5.setText("")
            self.Bu5.setText("")
        else:
            self.A5.setText(self.sqlfetchall[self.current_index][5][5:])
            self.Bu5.setText(self.sqlfetchall[self.current_index][5][1:2])

        self.question.setText(self.sqlfetchall[self.current_index][0])
        self.A1.setText(self.sqlfetchall[self.current_index][1][5:])
        self.A2.setText(self.sqlfetchall[self.current_index][2][5:])
        self.A3.setText(self.sqlfetchall[self.current_index][3][5:])
        self.A4.setText(self.sqlfetchall[self.current_index][4][5:])
        self.Bu1.setText(self.sqlfetchall[self.current_index][1][1:2])
        self.Bu2.setText(self.sqlfetchall[self.current_index][2][1:2])
        self.Bu3.setText(self.sqlfetchall[self.current_index][3][1:2])
        self.Bu4.setText(self.sqlfetchall[self.current_index][4][1:2])

    # 답 선택 시 이벤트
    def chooseNum(self, a):
        if self.sqlfetchall[self.current_index][8] == 1:
            if a == 1:
                self.label_8.setText("내가 고른 답: A")
            elif a == 2:
                self.label_8.setText("내가 고른 답: B")
            elif a == 3:
                self.label_8.setText("내가 고른 답: C")
            elif a == 4:
                self.label_8.setText("내가 고른 답: D")
            elif a == 5:
                self.label_8.setText("내가 고른 답: E")

        elif self.sqlfetchall[self.current_index][8] == 2:
            if a == 1:
                listA.append("A")
            elif a == 2:
                listA.append("B")
            elif a == 3:
                listA.append("C")
            elif a == 4:
                listA.append("D")
            elif a == 5:
                listA.append("E")
            if len(listA) == 1:
                self.label_8.setText("내가 고른 답: " + listA[0])
            else:
                self.label_8.setText("내가 고른 답: " + listA[0] + " " + listA[1])

    # 정답버튼 이벤트
    def showAnswer(self):
        if self.sqlfetchall[self.current_index][8] == 1:
            self.label_9.setText("정  답: " + self.sqlfetchall[self.current_index][6])
        elif self.sqlfetchall[self.current_index][8] == 2:
            self.label_9.setText("정  답: " + self.sqlfetchall[self.current_index][6] + " " + self.sqlfetchall[self.current_index][7])


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
